apiVersion: v1
kind: Service
metadata:
  name: video-service
  labels:
    app.kubernetes.io/name: video-service
    app.kubernetes.io/part-of: hangyin
spec:
  selector:
    app.kubernetes.io/name: video-service
  ports:
    - name: http
      port: 8082
      targetPort: http
