apiVersion: v1
kind: Service
metadata:
  name: interaction-service
  labels:
    app.kubernetes.io/name: interaction-service
    app.kubernetes.io/part-of: hangyin
spec:
  selector:
    app.kubernetes.io/name: interaction-service
  ports:
    - name: http
      port: 8090
      targetPort: http
