apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hangyin-mysql-data
  namespace: hangyin
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hangyin-live-mysql-data
  namespace: hangyin
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hangyin-minio-data
  namespace: hangyin
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
