apiVersion: v1
kind: Service
metadata:
  name: srs
  namespace: hangyin
spec:
  selector:
    app: srs
  ports:
    - name: rtmp
      port: 1935
      targetPort: 1935
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srs
  namespace: hangyin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srs
  template:
    metadata:
      labels:
        app: srs
    spec:
      containers:
        - name: srs
          image: ossrs/srs:5
          ports:
            - containerPort: 1935
            - containerPort: 8080
