spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hangyin_video?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mkj162829
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

app:
  upload-dir: backend/uploads

live:
  srs:
    rtmp-base-url: rtmp://localhost/live
    http-base-url: http://localhost:8081

minio:
  endpoint: http://localhost:9000
  public-base-url: http://localhost:8082/video
  access-key: minioadmin
  secret-key: minioadmin
  bucket: hangyin-video

video:
  chunk-dir: C:/hangyin/chunks
