spring.application.name=demo
video.transcode.enabled=true
video.transcode.ffmpeg-path=C:/Users/11616/AppData/Local/Microsoft/WinGet/Packages/Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe/ffmpeg-8.1.1-full_build/bin/ffmpeg.exe
video.transcode.timeout-seconds=300
